apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: NodePort
  selector:
    app: chat_server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
